blank_issues_enabled: true
contact_links:
  - name: Kako prispevam / Kako da doprinesem / How to contribute
    url: https://pfyber.github.io/ucila/prispevaj/
    about: Navodila za dodajanje učil in prevodov. / Uputstva. / Step-by-step guide.
